name: 'Cloudflare log fetcher'
description: 'Fetches Cloudflare deployment logs and prints with PR'
inputs:
  cf_account_id:  
    description: 'Cloudflare account id'
    required: true
  cf_project:  
    description: 'Cloudflare project name'
    required: true
  cf_log_id:  
    description: 'Cloudflare deployment log id'
    required: true
  cf_token:  
    description: 'Cloudflare API Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v2

    - name: Fetch and print logs
      shell: bash
      run: |
        echo ${{ steps.cf-url.URL }}
        curl --request GET --url "https://api.cloudflare.com/client/v4/accounts/${{inputs.cf_account_id}}/pages/projects/${{inputs.cf_project}}/deployments/${{inputs.cf_log_id}}/history/logs" --header "Authorization: Bearer ${{ inputs.cf_token }}" -o logs.json
        echo '--------- START LOGS ---------------'
        cat logs.json | jq -r '.result.data | sort_by(.ts)[] | .line' | while IFS= read -r line; do echo -e "$line"; done      
        echo '--------- END LOGS ---------------'
